/// Flutter icons ShieldCon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ShieldCon
///      fonts:
///       - asset: fonts/ShieldCon.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';
/// Allows custom shield icon.
// Did not want to delete in case it breaks other file.
class ShieldCon {
  ShieldCon._();

  static const _kFontFam = 'ShieldCon';
  static const String? _kFontPkg = null;

  static const IconData shield_alt = IconData(0xf3ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
